server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: my-agent
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据源配置
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://localhost:3306/my_agent?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver
      hikari:
        poolName: MySQLHikariPool
        maximumPoolSize: 10
        minimumIdle: 5
        connectionTimeout: 30000
        idleTimeout: 300000
        maxLifetime: 600000
        validationTimeout: 5000
        pool-name: MySQLHikariPool

    postgresql:
      jdbcUrl: jdbc:postgresql://rm-cn-9ky4de1x70004szo.rwlb.cn-chengdu.rds.aliyuncs.com:5432/my_agent
      username: agent_user
      password: agent_user123
      driverClassName: org.postgresql.Driver
      hikari:
        poolName: PostgreSQLHikariPool
        maximumPoolSize: 10
        minimumIdle: 5
        connectionTimeout: 30000
        idleTimeout: 300000
        maxLifetime: 600000
        validationTimeout: 5000
        pool-name: PostgreSQLHikariPool

  # Spring AI PGVector配置
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
        remove-existing-vector-store-table: false

    #    AI相关配置
    dashscope:
      api-key: sk-e1db0fd9aa6445c6a443764c9c23a8ac
      chat:
        options:
          model: qwen-plus

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.yu.my_agent.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false # 生产环境建议关闭
  global-config:
    db-config:
      id-type: AUTO
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: true # 关闭启动banner

logging:
  level:
    com.yu.my_agent.mapper: debug
#    org.springframework.ai.vectorstore: info

# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yu.my_agent.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn


# https://open.bochaai.com/
search-api:
  api_key_search_url: https://www.searchapi.io/api/v1/search
  api_key_search_api: Ra9LgZdHXDhadENVt8SzujHC
  api_key_bocha_url: https://api.bochaai.com/v1/web-search
  api_key_bocha_api: sk-ad4d4671791e40f6b4e9d4184a23e928